### ISSUE TITLE
Move default user admin from UserAdminApp to SignIn app

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/SignIn#1]
Each app should be able to work standalone.
SignIn app requires a user to work.

**Comment by warpech** [comment]
I think that this move was not correct. Actually it is the **User Admin** app that requires an "admin" user. 

**Sign In** app does not require any user to work. It will just not allow anyone to sign in, unless at least one SystemUser exists.

@miyconst can I revert it?

**Comment by miyconst** [comment]
Although it's logically, I would rather not. Very often we need a SignIn app and a default user, but installing UserAdmin just for this purpose is too troublesome. Also, the SignIn app no longer generates admin user automatically. Only when manually triggered by a URL.

**Comment by warpech** [comment]
Thank you for the input. I think it needs improvement in the long term, because right now it is difficult to understand how to get the UserAdmin app to work.

For the time being, I've just added instructions here: https://github.com/StarcounterPrefabs/UserAdmin/blob/master/README.md

**Comment by miyconst** [comment]
Okay. Actually the entire app asks to be re-done for long time.

**Comment by miyconst** [comment]
Do you think it's something @Joltrix can do?

**Comment by ubbeK** [comment]
I stumbled on the following code when playing around with our inside starcounter site and found this issue.

```cs
Handle.GET("/signin/generateadminuser", () =>
{
    if (Db.SQL("SELECT o FROM Simplified.Ring3.SystemUser o").First != null)
    {
        Handle.SetOutgoingStatusCode(403);
        return "Unable to generate admin user: database is not empty!";
    }

    SignInOut.AssureAdminSystemUser();

    return "Default admin user has been successfully generated.";
}, new HandlerOptions() {SkipRequestFilters = true});
```

It has already been some discussion regarding this here but I would like to point out that any Database that is running the `SignIn` app has this public handle to create a adminuser. Sure, if there already exists some SystemUser no harm will be done but it still feels kind of sketchy to leave this handle completely open.

**Comment by miyconst** [comment]
@ubbeK you are right. I can suggest to refuse to generate the default administrator, if the call is coming from everything but `localhost` (`127.0.0.1`). I have seen such security measure in many Microsoft solutions.

**Comment by ubbeK** [comment]
> I can suggest to refuse to generate the default administrator, if the call is coming from everything but localhost (127.0.0.1). I have seen such security measure in many Microsoft solutions.

That would do just fine.

**Comment by miyconst** [comment]
Implemented by @Joltrix, closing. Now it is possible to generate default admin user only from localhost.
