### ISSUE TITLE
Replace client side hashing with client side encryption

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/SignIn#34]
Right now SignIn app applies hash on top of the password two times: client side and server side. This makes it incompatible with the previous versions and other apps using password, such as UserAdmin.

@malx122 as I understood from your words that your main reason for double hashing is to obfuscate the real password, so it won't be easy to remember if seen by a chance.

Do you mind if I replace client side hashing with a simple encryption?

**Comment by malx122** [comment]
Yepp, I do mind.
We have already done the double hashing part so a change would mean that our users needs to change their password ONE MORE time.

But a simple encryption would also decrease security.

The reason for double hashing is not the security in our app(s), its for protecting the users password that can be used in other apps as well. And even if a simple (or advanced) encryption is used, it will never be as secure as a irreversible hash.

**Comment by miyconst** [comment]
I will keep the backward compatibility with the double-hashed version, so users won't need to set up the password again.

The security also won't be compromised, because the server side hashing will not be changed, and the password will still be saved as a hash, not as an encrypted value.

Do you have any other concerns?

**Comment by malx122** [comment]
I repeat myself, I don't think you understand the reason behind the client hashed password.
The security for the PASSWORD (not the server, not the database, not the databases data) will be less for an encryption than for a client side hash. Not much less, but less!

So why implement a worse solution than you already have...

(There is actually better solutions, but then we are talking really advanced things...)

**Comment by miyconst** [comment]
>So why implement a worse solution than you already have...

It is not that much worse, but give compatibility with other apps.

A starcounter app should not assume that another app of a certain version is running. A user password is a password, and user would expect to have same behavior by entering the same password in SignIn, UserAdmin, or CustomSignIn app.

If one of the apps changes the password to something else using some algorithm, then it became not compatible with other apps via shared database.

**Comment by miyconst** [comment]
@malx122 are you still against this replacement?

**Comment by mtornwall** [comment]
Sending `SHA1(password)` instead of `password` from the client confers no security benefits whatsoever. SHA1, particularly when unsalted, is practically broken for password hashing (albeit not for integrity checking) due to recent advances in hardware. Indeed, the best Bitcoin mining ASIC's (which must compute the slower function `SHA256(SHA256(x))` achieve 14 **trillion** hashes/sec.

You certainly *can* do hashing on the client, but the question is whether it adds any security. It really depends on whom you are protecting yourself against. The application developer? Nope, because they can inject arbitrary JavaScript into the page. An adversary who can intercept traffic (perhaps by compromising an SSL termination server)? Nope, same problem.

Note that I'm assuming use of HTTPS as a prerequisite; **no form of client-side hashing, no matter how sophisticated, is a valid substitute for using HTTPS**.

**Comment by mtornwall** [comment]
That being said, all objections that can be raised against client-side hashing are equally valid for (symmetric) client-side encryption.

**Comment by miyconst** [comment]
@mtornwall thank you for this nice short article, I am on your side.

The client side password encryption is to prevent people coming near by your machine to immediately remember the password when it is in the address bar or in the developers console.

I do agree that it does not add any extra security to the application, apart of making it more difficult to remember by a human when seeing on a screen.

**Comment by mtornwall** [comment]
> The client side password encryption is to prevent people coming near by your machine to immediately remember the password when it is in the address bar or in the developers console.

Aha, then I see the justification. :) However, I think this poses a problem in itself, as I noted in #46.

**Comment by warpech** [comment]
@miyconst for me, a fast solution is to replace client-side hashing with double server-side hashing. This should be backwards compatible.

**Comment by miyconst** [comment]
So, can we agree on the following:

- Completely remove client side hashing.
- Apply double hashing on server side to keep compatibility with the old password.
- Update SignIn app so it sends POST request instead of GET.
- Send username/password parameters as a POST parameter, not a query string value.

**Comment by andwah** [comment]
@warpech, @malx122  what do you think about @miyconst comment?

**Comment by warpech** [comment]
I agree. BTW a `DELETE` HTTP request can be used to log out a user.

**Comment by warpech** [comment]
I have done the code review of https://github.com/StarcounterPrefabs/SignIn/pull/50 and https://github.com/StarcounterPrefabs/Simplified/pull/32

Are the changes in UserAdmin and Registration also ready for code-review?

**Comment by miyconst** [comment]
>Are the changes in UserAdmin and Registration also ready for code-review?

Yes, but there are too few of the changes, so I didn't rise a pull request.

**Comment by warpech** [comment]
> Yes, but there are too few of the changes, so I didn't rise a pull request.

OK

**Comment by miyconst** [comment]
@warpech thank you for the reviews. Closing the issue.
