### ISSUE TITLE
Question : Where can i find documentation of this repository?

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterPrefabs/SignIn#39]

**Comment by warpech** [comment]
In the README.md. But it is very limited, I admit. See this: https://github.com/StarcounterPrefabs/SignIn/issues/33

I will try to do this ASAP.

Any particular questions?

**Comment by atifwaqar** [comment]
Is there any existing way to define user with specific roles? 
like Administrator, Manager, Viewer, Reporter, etc

**Comment by warpech** [comment]
We are working on it right now, but it will take few more weeks.

The concept is that:
- in SignIn app you just ask for username and password for not signed in user (do the **Authentication**)
- in your app you define permissions (do the **Authorization**)
- in UserAdmin app you create SystemUsers and SystemUserGroups and assign permissions to them in run time

**Comment by atifwaqar** [comment]
Nice, this is exactly what i was looking for. 
Do you have any demo code for what you explained above? any sort of sample code will be really really helpful.

**Comment by warpech** [comment]
This is work in progress. This will be available about one week from now. I will let you know, ok?

**Comment by atifwaqar** [comment]
Awesome. I'll be waiting for it then :) Thanks for the help.

**Comment by miyconst** [comment]
@warpech do we have any progress on this?

**Comment by warpech** [comment]
We have decided to follow the hard path: https://github.com/Starcounter/RebelsLounge/issues/41

Please follow the discussion there. @joozek78 updates the issue with information about progress. There should be some new stuff this week.

**Comment by miyconst** [comment]
Okay.. I have already read that issue, and participated.

**Comment by joozek78** [comment]
New Authorization library (along with docs) will be generally available probably in Q1 2017. It should be then referenced in this repository.
