### ISSUE TITLE
Signing after credentials autocomplete doesn't work

### ISSUE THREAD

**Issue by Mnosek** [StarcounterPrefabs/SignIn#42]
If the username and password is stored in the browser and filled out by autocomplete, sign in button doesn't work at the first time. Steps to reproduce:

1. Open Sign In form

1.  Sign in with correct credentials and save them in the browser

1. Sign out

1. Refresh the page (autocomplete should fill out the form automatically)

1. Click on "Sign In" button

1. Red alert that username is required appears.

I think that the browser doesn't fire "onChange" event after filling autocomplete form. Clicking on "Sign In" button should also send an update before firing actual action.

**Comment by warpech** [comment]
@Mnosek I've made fixes for this and #40 on SignIn `develop` branch. 

Could you please test (make sure to have **today's nightly**)

**Comment by Mnosek** [comment]
Thanks @warpech ! Autocomplete works fine on today's pnext.
