### ISSUE TITLE
Can not sign in a registered user

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/SignIn#43]
Using the Registration app v0.0.9 to register a new user.

That user fails to sign in (invalid password?).

related https://github.com/StarcounterPrefabs/Registration/issues/5

**Comment by stefanedqvist** [comment]
@miyconst can you fix this?

**Comment by miyconst** [comment]
Yes, but only in exchange of other projects.

**Comment by andwah** [comment]
*bump*

**Comment by miyconst** [comment]
This is the same as [Registered user can not login.](https://github.com/StarcounterPrefabs/Registration/issues/5). Closing.

**Comment by andwah** [comment]
I think the problem is in this app not in registration app.

**Comment by andwah** [comment]
i will assign this to @miyconst  as he has maybe a solution after the meeting with jocke.

**Comment by miyconst** [comment]
@andwah, yes, this issue is in SignIn app, but the reason is the same. And here is already an issue for it - [Replace client side hashing with client side encryption](https://github.com/StarcounterPrefabs/SignIn/issues/34).

**Comment by andwah** [comment]
As i understand it this is a bug/showstopper and the [Replace client side hashing with client side encryption](https://github.com/StarcounterPrefabs/SignIn/issues/34). is an enhancement.

**Comment by miyconst** [comment]
Yes, but this showstopper appeared because of the double hashing in the SignIn app.

**Comment by andwah** [comment]
We need a common solution so apps can work together. How can this be done?

if this app is broken we need to fix it ASAP.

**Comment by miyconst** [comment]
Please read my comment in the issue linked above - https://github.com/StarcounterPrefabs/SignIn/issues/34#issuecomment-258123328.

It should fix compatibility issue between SignIn, UserAdmin, Registration. Just need a confirmation from @warpech and @malx122.
