### ISSUE TITLE
Allow requests to /signin/generateadminuser from localhost only

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/SignIn#45]
Original issue: https://github.com/StarcounterPrefabs/SignIn/issues/1

**Comment by Joltrix** [comment]
Implemented in [StarcounterPrefabs/SignIn/a750754](https://github.com/StarcounterPrefabs/SignIn/commit/a750754e9c2af6502b78d717096850ccbcef363d)

**Comment by miyconst** [comment]
Thank you @Joltrix, closing the issue.
