### ISSUE TITLE
The password (hash) shouldn't be sent as part of the URL

### ISSUE THREAD

**Issue by mtornwall** [StarcounterPrefabs/SignIn#46]
I noticed that the username and password are sent to the server by asking Puppet to load `/some/url/username/passwordhash`. This is problematic as many web servers save the path and query string to their log files where an attacker or rogue employee might be able to retrieve it later.

**Comment by warpech** [comment]
@miyconst is working on it (#50)

**Comment by miyconst** [comment]
It is already implemented in the [scrypt](https://github.com/StarcounterPrefabs/SignIn/tree/scrypt) branch. Available for test.

**Comment by warpech** [comment]
I have done the code review of https://github.com/StarcounterPrefabs/SignIn/pull/50 and https://github.com/StarcounterPrefabs/Simplified/pull/32

Are the changes in UserAdmin and Registration also ready for code-review?

**Comment by warpech** [comment]
This was fixed in PR #50.
