### ISSUE TITLE
Merge master branch to develop, then develop to master

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/SignIn#47]
@Joltrix Similarly to what I pointed out in KitchenSink, please merge master branch to develop branch. Then merge develop to master, to have a clean state of the repo.

In future, please always do the work in the apps in the develop branch (and feature branches started from that branch).

Branching guidelines: https://github.com/StarcounterPrefabs/Guidelines/blob/master/branching.md

**Comment by Joltrix** [comment]
@warpech I apologize! Out of habit (in the palma project) I just commited it to master.

I merged them now, so they should be the same! (note* they should! I think my github is a bit bugged, so I can update master from develop, and then update develop from master in an endless loop... Or should this be possible? In any case, I've updated them! :D )

If they're not merged, or if I did anything wrong, please tell me!

**Comment by warpech** [comment]
Thanks!

>I merged them now, so they should be the same! (note* they should! I think my github is a bit bugged, so I can update master from develop, and then update develop from master in an endless loop...

This is normal. The branches were changed in parallel, which caused a *fast-forward* merge to be impossible. Hence, *recursive* merge was applied by git. After *recursive*, the merge itself becomes a commit. This will cause this "loop" effect. It is nothing wrong, just we will have to live with it from now on.

Normally only merges `develop -> master` will be done.

**Comment by warpech** [comment]
Actually I lied. After a *recursive* merge from `develop -> master`, you can do a *fast forward* merge from `master -> develop`. From now on, the two branches are in sync again.

I just did it.

Future merges `develop -> master` will be fast forward.

**Comment by Joltrix** [comment]
Ah phew, luckily I didn't break anything!

Thanks for fixing! :D, I'll be careful to only commit to develop from now on, and then update master from there
