### ISSUE TITLE
Generate admin users

### ISSUE THREAD

**Issue by aloscha** [StarcounterPrefabs/SignIn#52]
Right now there only way to generate admin user is type: `/signin/generateadminuser`. And there are condition `Db.SQL("SELECT o FROM Simplified.Ring3.SystemUser o").First != null`.

In our project, we have possibility to run application with seed data (also we've create test user for start). So when we start signin, then our app with seed data, the `SystemUser` table is not empty and we couldn't generate the admin user.

To resolve that we should start SignIn than, generate admin user, than run our app with seed data. But more complex solution will be:

1. Change condition if admin user doesn't exists than, create user
2. Generate admin user on start of SignIn app

cc @miyconst @warpech

**Comment by miyconst** [comment]
This is a security feature. If there is a user in the table, then maybe it is a local admin which has access to the users and he/she deleted the default administrator. Generating it once again is not safe.

If you have the default database and/or user generation, then you should take care about the admin user as well.

**Comment by aloscha** [comment]
But adding handler outside to generate any user is not security safe, at all. Maybe better will be adding some parameter to run application like `SingIn.exe -generateAdmin`?

**Comment by miyconst** [comment]
>But adding handler outside to generate any user is not security safe

It is safe enough, considering that it will generate a user only if:

- There are no other users.
- The request is coming from localhost.

**Comment by per-samuelsson** [comment]
Does this discussion relate to this: https://github.com/Starcounter/CompanyTrack/issues/179

It's an old issue about the problems with automatic data assurance pattern, and also touches https://github.com/StarcounterPrefabs/SignIn/issues/11.

**Comment by miyconst** [comment]
Yes, it is related, but from other side. I doubt that anything will be changed in scope of this issue.

@aloscha do you still insist on the points from the main comments?

>1. Change condition if admin user doesn't exists than, create user
>2. Generate admin user on start of SignIn app

**Comment by aloscha** [comment]
I think we can stay with current version @miyconst
