### ISSUE TITLE
Replace ImageURL with Illustration

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/SignIn#58]
Since now ImageURL is obsolete, its occurrence in SignIn needs to be replaced with Illustration (if there is an illustration to a Person associated with the SystemUser class).

Otherwise SignIn does not compile with last changes in Simplified.

I can explain more if needed.

@diliger can you please do that?

**Comment by diliger** [comment]
If there is no `Illustration` for the `Person`, should I request **Gravatar** for empty string?
`if (string.IsNullOrEmpty(this.ImageUrl))
 {
      this.ImageUrl = Utils.GetGravatarUrl(string.Empty);
}`

**Comment by diliger** [comment]
PR #59

**Comment by diliger** [comment]
Can be closed now?

**Comment by warpech** [comment]
No, because the PR is still ongoing.

**Comment by warpech** [comment]
Closing as done
