### ISSUE TITLE
Sign-in form does not work when refreshing

### ISSUE THREAD

**Issue by un-tone** [StarcounterPrefabs/SignIn#64]
### Steps to reproduce
1. Start Launcher `develop` branch
2. Start SignIn `develop` branch
3. Go to `http://localhost:8080/launcher`
4. Click on the "User" icon
5. Press "Forgot password?" button, the URL changes to `http://localhost:8080/signin/signinuser?/launcher`
6. Press F5 to reload the page

### Expected result
The page should correctly reload with the "Sign In" view.

### Actual result
When you reload the page at this point it shows JSON data

##### Involved apps' version

 - StarcounterPrefabs/Launcher@54b6d0717c34856add753a4a1bb0945ea472094d
 - StarcounterPrefabs/SignIn@9acd76216501acbe4aaf9f9ff06fc5729ce91fa1
 
##### Browsers affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Screenshot
![signinissuereloadform](https://cloud.githubusercontent.com/assets/1625378/22595556/03de3aa0-ea39-11e6-832c-02f08adbeb38.png)

**Comment by warpech** [comment]
Closing as done.
